spring:
  application:
    name: id-service

server:
  port: 10022

# 指定注册到哪个注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10010/eureka/
  instance:
    prefer-ip-address: true  #注册中心保存我的ip

mybatis:
  type-aliases-package: com.yhz.idservice.entity
  mapper-locations: classpath:mapper/*.xml