package com.yhz.idservice.entity;

public class Id {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idm_id.id
     *
     * @mbggenerated Sun May 10 20:15:22 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idm_id.name
     *
     * @mbggenerated Sun May 10 20:15:22 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idm_id.age
     *
     * @mbggenerated Sun May 10 20:15:22 CST 2020
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idm_id.gender
     *
     * @mbggenerated Sun May 10 20:15:22 CST 2020
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idm_id.id_no
     *
     * @mbggenerated Sun May 10 20:15:22 CST 2020
     */
    private String idNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idm_id.phone_number
     *
     * @mbggenerated Sun May 10 20:15:22 CST 2020
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idm_id.is_deleted
     *
     * @mbggenerated Sun May 10 20:15:22 CST 2020
     */
    private Byte isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idm_id.id
     *
     * @return the value of idm_id.id
     *
     * @mbggenerated Sun May 10 20:15:22 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idm_id.id
     *
     * @param id the value for idm_id.id
     *
     * @mbggenerated Sun May 10 20:15:22 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idm_id.name
     *
     * @return the value of idm_id.name
     *
     * @mbggenerated Sun May 10 20:15:22 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idm_id.name
     *
     * @param name the value for idm_id.name
     *
     * @mbggenerated Sun May 10 20:15:22 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idm_id.age
     *
     * @return the value of idm_id.age
     *
     * @mbggenerated Sun May 10 20:15:22 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idm_id.age
     *
     * @param age the value for idm_id.age
     *
     * @mbggenerated Sun May 10 20:15:22 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idm_id.gender
     *
     * @return the value of idm_id.gender
     *
     * @mbggenerated Sun May 10 20:15:22 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idm_id.gender
     *
     * @param gender the value for idm_id.gender
     *
     * @mbggenerated Sun May 10 20:15:22 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idm_id.id_no
     *
     * @return the value of idm_id.id_no
     *
     * @mbggenerated Sun May 10 20:15:22 CST 2020
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idm_id.id_no
     *
     * @param idNo the value for idm_id.id_no
     *
     * @mbggenerated Sun May 10 20:15:22 CST 2020
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo == null ? null : idNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idm_id.phone_number
     *
     * @return the value of idm_id.phone_number
     *
     * @mbggenerated Sun May 10 20:15:22 CST 2020
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idm_id.phone_number
     *
     * @param phoneNumber the value for idm_id.phone_number
     *
     * @mbggenerated Sun May 10 20:15:22 CST 2020
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idm_id.is_deleted
     *
     * @return the value of idm_id.is_deleted
     *
     * @mbggenerated Sun May 10 20:15:22 CST 2020
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idm_id.is_deleted
     *
     * @param isDeleted the value for idm_id.is_deleted
     *
     * @mbggenerated Sun May 10 20:15:22 CST 2020
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }
}