package com.yhz.idservice.mapper;

import com.yhz.idservice.entity.Id;
import com.yhz.idservice.entity.IdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idm_id
     *
     * @mbggenerated Sun May 10 20:15:22 CST 2020
     */
    int countByExample(IdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idm_id
     *
     * @mbggenerated Sun May 10 20:15:22 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idm_id
     *
     * @mbggenerated Sun May 10 20:15:22 CST 2020
     */
    int insert(Id record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idm_id
     *
     * @mbggenerated Sun May 10 20:15:22 CST 2020
     */
    int insertSelective(Id record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idm_id
     *
     * @mbggenerated Sun May 10 20:15:22 CST 2020
     */
    List<Id> selectByExample(IdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idm_id
     *
     * @mbggenerated Sun May 10 20:15:22 CST 2020
     */
    Id selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idm_id
     *
     * @mbggenerated Sun May 10 20:15:22 CST 2020
     */
    int updateByExampleSelective(@Param("record") Id record, @Param("example") IdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idm_id
     *
     * @mbggenerated Sun May 10 20:15:22 CST 2020
     */
    int updateByExample(@Param("record") Id record, @Param("example") IdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idm_id
     *
     * @mbggenerated Sun May 10 20:15:22 CST 2020
     */
    int updateByPrimaryKeySelective(Id record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idm_id
     *
     * @mbggenerated Sun May 10 20:15:22 CST 2020
     */
    int updateByPrimaryKey(Id record);
}